### ISSUE TITLE
Change outdir subdirectory names to module names

### ISSUE THREAD

**Issue by jmuhlich** [nf-core/mcmicro#19]
### Description of the bug

Subdirectories should be named after the corresponding module name, with possible parallel outputs from different tools under different names or sub-sub-directories therein. E.g. instead of `ashlar/` we should have `registration/`.

**Comment by RobJY** [comment]
I've pushed a fix that moves ashlar output to $outdir/registration/ashlar

I'm thinking for the other modules we would have superdirectories named:
- `input_validation` for input_check.nf
- `illumination_correction` for basicpy
- `segmentation` for deepcell_mesmer
- `quantification` for mcquant

Please let me know if I should change any of the above.

**Comment by RobJY** [comment]
just pushed updated code to fix this as described above
