### ISSUE TITLE
Set up test profile

### ISSUE THREAD

**Issue by jmuhlich** [nf-core/mcmicro#20]
### Description of feature

The `test` profile should run our small tonsil test image data through as much of the pipeline as we have working.

**Comment by RobJY** [comment]
From the rnaseq repo it looks like we should have the input parameters in the test-dataset repo so we can use URLs in test.config and related files.  Is this correct or should I just try to use the files from our assets directory?

Should we do multiple test profiles like:
- test: minimal run using 1 row per sample per cycle samplesheet with no illumination correction so we just need `input_cycle` and `marker_sheet` parameters.
- test_cycle_basicpy: same as test, but include basicpy illumination correction
- test_sample_basicpy: minimal run using 1 row per sample samplesheet with basicpy illumination correction

**Comment by RobJY** [comment]
We may want to improve the quality of the sample and marker sheets before we put them in the test data repo since I just put in garbage values to have something to run.

**Comment by RobJY** [comment]
I'm already using URLs for the 1 row per sample per cycle samplesheets, but I still have full paths in the ones for 1 row per sample because they require an image_directory.  I guess we could specify an S3 bucket 'directory'?  Is there a better way to do this?

**Comment by jmuhlich** [comment]
I hacked something together in the recent PR that was just merged to dev. It uses a local sample sheet that's committed to the mcmicro repo, but I reference it via its `raw.githubusercontent.com` URL. I think the correct long-term solution is to commit the test samplesheets and marker sheets to the (as yet nonexistent) mcmicro branch in the test-datasets repo and reference them by https URL from there.

**Comment by jmuhlich** [comment]
Since #26 also introduces a minimally functional `test` profile and our CI now requires it to run successfully, I'll close this. We can improve the test profile setup with a more expansive sample sheet as time goes on.
